version: '2'
services:
  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8180:8080"
      - "7177:7077"
      - "4140:4040"
    volumes:
      - /D/Docker/wsl/volumes/spark:/data
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8181:8081"
    volumes:
      - /D/Docker/wsl/volumes/spark:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8182:8081"
    volumes:
      - /D/Docker/wsl/volumes/spark:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"  
  spark-worker-3:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8183:8081"
    volumes:
      - /D/Docker/wsl/volumes/spark:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"